version: '3.8'

services:
  # Browser-Use MCP Server with VNC for visual debugging
  browser-use-mcp:
    image: ghcr.io/co-browser/browser-use-mcp-server:latest
    container_name: browser-use-mcp
    ports:
      - "5900:5900"    # VNC port for visual debugging
      - "8765:8765"    # WebSocket port for MCP
    environment:
      - DISPLAY=:99
      - VNC_PASSWORD=gemini123
      - BROWSER_USE_HEADLESS=false
      - BROWSER_USE_SAVE_VIDEOS=true
      - BROWSER_USE_VIDEO_DIR=/videos
      - BROWSER_USE_SAVE_ARTIFACTS=true
      - BROWSER_USE_ARTIFACTS_DIR=/artifacts
      - MCP_TRANSPORT=stdio
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    volumes:
      - ./browser-recordings:/videos
      - ./browser-artifacts:/artifacts
      - ./browser-data:/data
    networks:
      - browser-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Playwright MCP Server for advanced browser automation
  playwright-mcp:
    build:
      context: .
      dockerfile: docker/playwright-mcp.Dockerfile
    container_name: playwright-mcp
    ports:
      - "3001:3001"    # HTTP port for MCP
    environment:
      - MCP_TRANSPORT=http
      - MCP_HTTP_PORT=3001
      - BROWSER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
      - BROWSER_HEADLESS=false
      - BROWSER_SLOWMO=100
    volumes:
      - ./playwright-data:/data
      - ./screenshots:/screenshots
    networks:
      - browser-network
    restart: unless-stopped

networks:
  browser-network:
    driver: bridge